package br.com.willendary.designacoesjw

import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import br.com.willendary.designacoesjw.data.Meeting
import java.text.SimpleDateFormat
import java.util.*

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun App(vm: AppViewModel = viewModel()) {
    var tab by remember { mutableIntStateOf(0) }
    Scaffold(
        topBar = { TopAppBar(title = { Text("Designações JW") }) },
        bottomBar = {
            NavigationBar {
                listOf("Início", "Irmãos", "Privilégios", "Histórico").forEachIndexed { i, label ->
                    NavigationBarItem(selected = tab == i, onClick = { tab = i },
                        icon = { Text(listOf("⌂", "●", "✓", "▣")[i]) }, label = { Text(label) })
                }
            }
        }
    ) { padding -> Box(Modifier.padding(padding).fillMaxSize()) {
        when (tab) { 0 -> HomeScreen(vm); 1 -> BrothersScreen(vm); 2 -> PrivilegesScreen(vm); 3 -> HistoryScreen(vm) }
    }}
}

@Composable
private fun HomeScreen(vm: AppViewModel) {
    val context = LocalContext.current
    var date by remember { mutableStateOf(SimpleDateFormat("dd/MM/yyyy", Locale("pt-BR")).format(Date())) }
    var type by remember { mutableStateOf("Reunião") }
    var generated by remember { mutableStateOf<Meeting?>(null) }

    Column(Modifier.padding(20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
        Text("Painel", style = MaterialTheme.typography.headlineSmall)
        Text("${vm.brothers.value.count { it.active }} irmãos ativos • ${vm.privileges.value.size} privilégios")
        OutlinedTextField(date, { date = it }, label = { Text("Data da reunião") }, modifier = Modifier.fillMaxWidth())
        OutlinedTextField(type, { type = it }, label = { Text("Tipo") }, modifier = Modifier.fillMaxWidth())
        Button({ generated = vm.generateMeeting(date, type) }, Modifier.fillMaxWidth()) { Text("Gerar designações") }

        generated?.let { meeting ->
            Text("Designações geradas", style = MaterialTheme.typography.titleLarge)
            meeting.assignments.forEach { a ->
                val b = vm.brothers.value.find { it.id == a.brotherId }
                val p = vm.privileges.value.find { it.id == a.privilegeId }
                Text("• ${p?.name ?: "Privilégio"} — ${b?.name ?: "Irmão"}")
            }
            Button({
                val msg = buildString {
                    append("Designações — ${meeting.type} em ${meeting.date}\n\n")
                    meeting.assignments.forEach { a ->
                        val b = vm.brothers.value.find { it.id == a.brotherId }
                        val p = vm.privileges.value.find { it.id == a.privilegeId }
                        append("${p?.name}: ${b?.name}\n")
                    }
                }
                context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("https://wa.me/?text=${Uri.encode(msg)}")))
            }, Modifier.fillMaxWidth()) { Text("Compartilhar pelo WhatsApp") }
        }
    }
}

@Composable
private fun BrothersScreen(vm: AppViewModel) {
    var name by remember { mutableStateOf("") }
    var phone by remember { mutableStateOf("") }
    Column(Modifier.padding(20.dp)) {
        Text("Irmãos", style = MaterialTheme.typography.headlineSmall)
        Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
            OutlinedTextField(name, { name = it }, label = { Text("Nome") }, modifier = Modifier.weight(1f))
            OutlinedTextField(phone, { phone = it }, label = { Text("WhatsApp") }, modifier = Modifier.weight(1f))
        }
        Button({ vm.addBrother(name, phone); name = ""; phone = "" }) { Text("Adicionar") }
        LazyColumn { items(vm.brothers.value) { b ->
            ListItem({ Text(b.name) }, supportingContent = { Text(if (b.phone.isBlank()) "Sem WhatsApp" else b.phone) })
            HorizontalDivider()
        }}
    }
}

@Composable
private fun PrivilegesScreen(vm: AppViewModel) {
    var name by remember { mutableStateOf("") }
    var quantity by remember { mutableStateOf("1") }
    Column(Modifier.padding(20.dp)) {
        Text("Privilégios", style = MaterialTheme.typography.headlineSmall)
        OutlinedTextField(name, { name = it }, label = { Text("Nome") }, modifier = Modifier.fillMaxWidth())
        OutlinedTextField(quantity, { quantity = it.filter(Char::isDigit) }, label = { Text("Quantidade necessária") }, modifier = Modifier.fillMaxWidth())
        Button({ vm.addPrivilege(name, quantity.toIntOrNull() ?: 1); name = ""; quantity = "1" }) { Text("Adicionar") }
        LazyColumn { items(vm.privileges.value) { p ->
            ListItem({ Text(p.name) }, supportingContent = { Text("Necessários: ${p.quantity}") })
            vm.brothers.value.forEach { b ->
                Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    Text(b.name, Modifier.padding(start = 16.dp))
                    Checkbox(p.id in b.privileges, { vm.togglePrivilege(b.id, p.id) })
                }
            }
            HorizontalDivider()
        }}
    }
}

@Composable
private fun HistoryScreen(vm: AppViewModel) {
    LazyColumn(Modifier.padding(20.dp)) {
        item { Text("Histórico", style = MaterialTheme.typography.headlineSmall); Spacer(Modifier.height(12.dp)) }
        items(vm.meetings.value.reversed()) { m ->
            Card(Modifier.fillMaxWidth().padding(bottom = 10.dp)) {
                Column(Modifier.padding(16.dp)) {
                    Text("${m.type} — ${m.date}", style = MaterialTheme.typography.titleMedium)
                    m.assignments.forEach { a ->
                        val b = vm.brothers.value.find { it.id == a.brotherId }
                        val p = vm.privileges.value.find { it.id == a.privilegeId }
                        Text("${p?.name}: ${b?.name}")
                    }
                }
            }
        }
    }
}
